grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - "monitoring.playground.local"
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true